### ISSUE TITLE
unused property in mapping

### ISSUE THREAD

**Issue by coret** [netwerk-digitaal-erfgoed/modemuze-pipeline#1]
https://github.com/netwerk-digitaal-erfgoed/modemuze-pipeline/blob/19d20a7f1e9ef54acc722d3020e509e819f7fb80/mappings/toSchema.rq#L43

The `?indentifier` [sic] property could be used in the construct part as value for `schema:identifier`

**Comment by EnnoMeijers** [comment]
Thanks for having a look at it! Your completely right, at some point this was my intention, without the spelling mistake of course ;). I updated the query.
